### ISSUE TITLE
Deploy app via TestFlight

### ISSUE THREAD

**Issue by markdboyd** [developmentseed/libra-alexa-react-native#3]
Figure out how to deploy the app with TestFlight so that other developers/team members can easily install and test it 

To do

- [x] Integrate the app with TestFlight
- [x] Do an initial test deployment with TestFlight

**Comment by markdboyd** [comment]
I did some research here and wanted to summarize my findings.

- To deploy our app for testing via TestFlight, we need an Apple developer account, which has a $100 yearly cost that we'd have to pay
- The first build of app uploaded to TestFlight has to pass a [review by Apple before it can be tested](https://help.apple.com/app-store-connect/#/devdc42b26b8). Anecdotally, [some people claim this process has taken anywhere from matter of a hours to a few days](https://apple.stackexchange.com/questions/153137/how-long-does-the-new-testflight-beta-review-process-usually-take/196118) 
- Testers have to be added by the TestFlight administrator(s), there is no mechanism for them to opt-in.

I also looked into how distributing the app for testing on Android could be done. There are a number of TestFlight competitors, such as [TestFairy](https://www.testfairy.com/), but they have varying pricing strategies and integrations that would need to be investigated. Apparently [Google Play allows for distributing beta releases of apps](https://support.google.com/googleplay/android-developer/answer/3131213?hl=en), which has a $25 registration fee. Alternatively, the simplest option would be using React Native build tools to generate an `.apk` file that is emailed directly to testers.

One alternative solution for distributing the app for iOS and Android would be to use Microsoft's Appcenter (https://appcenter.ms/), which supports automated builds of React Native apps for iOS and Android. It also makes it easy [to distribute `.ipa` files for iOS and `.apk` files for Android manually via email](https://docs.microsoft.com/en-us/appcenter/distribution/). I have used Appcenter in the past and it works well. Appcenter also supports integration with TestFlight, though likely we would not want/need that for now.

**Comment by ianschuler** [comment]
@markdboyd i defer to you and the team on the best way to distribute. The cost points here seem reasonable.

For SatSummit:
1. It is not critical to have this working on both ecosystems. We are showing the art of the possible, not claiming to have a production tool. IOS is preferred (because of point 2), but I'll take whichever ecosystem I can get.
2. It is not critical that this be available on an app store. In case it isn't, then we should a) install it on the phones of devseed team members and b) have a few devices (phone and/or ipad) available at our booth for demos. cc @ldgillen

**Comment by ldgillen** [comment]
Agree would be great to have it on a range of devices for SatSummit. I also think we should do a demo to the team on Monday/Tuesday so folks know how to work it on their own device. 

@markdboyd wanna own the demo to the team?

**Comment by markdboyd** [comment]
@ianschuler - OK. I will prioritize trying to get some basic method of distribution (even for our internal team) working, likely using Appcenter. Beyond that, do you want to pay the $100 to set up an Apple Developer account so we can try to get the app on TestFlight? If we can get the app submitted/approved before Wednesday, then it would be the lowest friction option for conference attendees with iOS devices to install/test the app, but there's no guarantee it would be approved by then

@ldgillen - Yeah. I can own doing a demo to the team on Tuesday.

**Comment by ianschuler** [comment]
>do you want to pay the $100 to set up an Apple Developer account so we can try to get the app on TestFlight

@markdboyd sure. let me know if you need a DS credit card

**Comment by markdboyd** [comment]
Progress update:

- With @olafveerman's help, we have linked the repo with Appcenter so we can do builds there
- Started the Apple Developer enrollment process so we can sign our iOS builds and distribute them via TestFlight
  - To start the enrollment process, we had to enable 2FA on the Devseed apple account, which I temporarily linked to my phone number
  - We received a phone call saying that @scisco has to do something before enrollment can continue (cc @drewbo for context)

To do:

- Verify we can get a working, un-signed build in Appcenter for iOS
- Once Apple developer account is approved, link our credentials with the app so it can be signed 
- Add TestFlight as a distribution mechanism in Appcenter

**Comment by markdboyd** [comment]
Update

- Got Apple developer account fully set up
- Got the iOS build working in Appcenter
- Tried to [connect Appcenter to TestFlight ](https://docs.microsoft.com/en-us/appcenter/distribution/stores/apple) but it would not work because TFA is enabled for our Apple developer account and Appcenter does not support that
  - If we have another team member who has not enabled TFA for their Apple ID, we can add them as an admin for our organization and they could connect Appcenter to TestFlight
- Since Appcenter and Testflight aren't connected, I follow [these manual steps to get the app on Testflight](https://medium.com/@dmathewwws/steps-to-put-your-app-on-testflight-and-then-the-ios-app-store-10a7996411b1)
  - The app is in "Waiting for review" status, which supposedly takes a few days
  - I added @ianschuler and @scisco as testers, so when the app passes review, they should be able to test by installing TestFlight on an iOS device

**Comment by markdboyd** [comment]
The app passed TestFlight beta review yesterday, 9/16, so it can now be installed/tested via TestFlight.

@scisco confirmed that he can install the app on his phone and the most basic functionality is working. We will need to update the build with the latest UI work and re-push to TestFlight, but I think our integration with TestFlight at this point is successful and this ticket can be closed.
